# vim:fileencoding=utf-8:foldmethod=marker
# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf

#: Fonts {{{
font_size 18
font_family Mononoki Nerd Font Mono Bold Italic
#italic_font Mononoki Nerd Font Mono Italic
#bold_font Mononoki Nerd Font Mono Bold
bold_italic_font Mononoki Nerd Font Mono Bold Italic
disable_ligatures cursor


#window
hide_window_decorations titlebar-only
window_padding_width 15
background_opacity 1.0
background_blur 30
dynamic_background_opacity no
#tab bar
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

#cursor
#cursor_trail 1

# general key mapping
macos_option_as_alt yes 

# vim key mapping
map cmd+s send_text all \e:w\r
map cmd+p send_text all :Telescope find_files\r
map cmd+shift+f send_text all :Telescope live_grep\r
map cmd+b send_text all :Neotree toggle\r

# tmux key mapping
map cmd+1 combine : send_key ctrl+b : send_key 1
map cmd+2 combine : send_key ctrl+b : send_key 2
map cmd+3 combine : send_key ctrl+b : send_key 3
map cmd+4 combine : send_key ctrl+b : send_key 4
map cmd+5 combine : send_key ctrl+b : send_key 5
map cmd+6 combine : send_key ctrl+b : send_key 6
map cmd+7 combine : send_key ctrl+b : send_key 7
map cmd+8 combine : send_key ctrl+b : send_key 8
map cmd+9 combine : send_key ctrl+b : send_key 9

# 分屏
map cmd+h combine : send_key ctrl+b : send_key "  # 水平分屏
map cmd+v combine : send_key ctrl+b : send_key %   # 垂直分屏
map cmd+x combine : send_key ctrl+b : send_key x   # 关闭面板

# 面板切换
map cmd+up    combine : send_key ctrl+b : send_key up
map cmd+down  combine : send_key ctrl+b : send_key down
map cmd+left  combine : send_key ctrl+b : send_key left
map cmd+right combine : send_key ctrl+b : send_key right

# 调整面板大小
map cmd+ctrl+up    combine : send_key ctrl+b : send_key ctrl+up
map cmd+ctrl+down  combine : send_key ctrl+b : send_key ctrl+down
map cmd+ctrl+left  combine : send_key ctrl+b : send_key ctrl+left
map cmd+ctrl+right combine : send_key ctrl+b : send_key ctrl+right

# 窗口管理
map cmd+n       combine : send_key ctrl+b : send_key c    # 新建窗口
map cmd+w       combine : send_key ctrl+b : send_key &    # 关闭窗口
map cmd+p       combine : send_key ctrl+b : send_key p    # 上一个窗口
map cmd+shift+n combine : send_key ctrl+b : send_key n    # 下一个窗口

# 其他功能
map cmd+z combine : send_key ctrl+b : send_key z  # 最大化/恢复面板
map cmd+, combine : send_key ctrl+b : send_key ,  # 重命名窗口
map cmd+l combine : send_key ctrl+b : send_key w  # 显示窗口列表

