version: '3.8'
services:
  cpp-dev:
    build:
      context: .
      dockerfile: 02-full-cpp/Dockerfile.fedora-latest
    privileged: true
    volumes:
      - ${HOME}/workspace:/workspace:cached
    environment:
      - TZ=Asia/Shanghai
    working_dir: /workspace
    command: tail -f /dev/null
    tty: true
